import type {
  ProfessionalQualityDimensionId,
  ProfessionalTextPackageField,
  ProfessionalTextTypeContract,
  VideoType,
} from '@shared/types.js';

export const PROFESSIONAL_TEXT_PACKAGE_FIELDS: ProfessionalTextPackageField[] = [
  'creative_brief',
  'audience_promise',
  'premise_or_core_question',
  'theme_statement',
  'truth_and_adaptation_contract',
  'structure_outline',
  'sequence_beats',
  'scene_breakdown',
  'full_text',
  'dialogue_or_narration_pass',
  'director_text_plan',
  'continuity_ledger',
  'quality_report',
  'coverage_report',
  'revision_trace',
  'delivery_text_package',
];

const COMMON_HARD_GATES = [
  '未知、传说或虚构内容不得写成确证事实',
  '必须明确受众、时长和片型承诺',
  'full_text 不得是大纲、资料摘要或内部分析',
  '场景必须有行动、变化或推进功能',
  '分场、正文、GEARS 分段和交付文本不得互相矛盾',
  '视觉提示不得混入来源说明、质量标签、TODO 或内部字段',
  '不得使用未授权原文、角色、样片剧情或具体作者风格仿写',
  '不得缺少片型专属必交项',
];

const DRAMA_WEIGHTS: Record<ProfessionalQualityDimensionId, number> = {
  creative_brief_and_audience_promise: 8,
  premise_and_theme_unity: 10,
  structure_causality_and_pacing: 15,
  character_agency_and_relationship_change: 12,
  scene_function_visible_action_and_blocking: 12,
  dialogue_narration_and_subtext: 10,
  emotional_curve_and_aftertaste: 10,
  cultural_fact_and_adaptation_boundary: 10,
  production_executability: 8,
  originality_and_distinctiveness: 5,
};

const AI_COMIC_WEIGHTS: Record<ProfessionalQualityDimensionId, number> = {
  creative_brief_and_audience_promise: 8,
  premise_and_theme_unity: 9,
  structure_causality_and_pacing: 15,
  character_agency_and_relationship_change: 12,
  scene_function_visible_action_and_blocking: 15,
  dialogue_narration_and_subtext: 12,
  emotional_curve_and_aftertaste: 9,
  cultural_fact_and_adaptation_boundary: 7,
  production_executability: 8,
  originality_and_distinctiveness: 5,
};

const PROMO_WEIGHTS: Record<ProfessionalQualityDimensionId, number> = {
  creative_brief_and_audience_promise: 10,
  premise_and_theme_unity: 12,
  structure_causality_and_pacing: 13,
  character_agency_and_relationship_change: 6,
  scene_function_visible_action_and_blocking: 14,
  dialogue_narration_and_subtext: 12,
  emotional_curve_and_aftertaste: 9,
  cultural_fact_and_adaptation_boundary: 10,
  production_executability: 9,
  originality_and_distinctiveness: 5,
};

const NONFICTION_WEIGHTS: Record<ProfessionalQualityDimensionId, number> = {
  creative_brief_and_audience_promise: 10,
  premise_and_theme_unity: 12,
  structure_causality_and_pacing: 15,
  character_agency_and_relationship_change: 4,
  scene_function_visible_action_and_blocking: 12,
  dialogue_narration_and_subtext: 10,
  emotional_curve_and_aftertaste: 6,
  cultural_fact_and_adaptation_boundary: 16,
  production_executability: 10,
  originality_and_distinctiveness: 5,
};

const SPATIAL_WEIGHTS: Record<ProfessionalQualityDimensionId, number> = {
  creative_brief_and_audience_promise: 8,
  premise_and_theme_unity: 12,
  structure_causality_and_pacing: 12,
  character_agency_and_relationship_change: 3,
  scene_function_visible_action_and_blocking: 18,
  dialogue_narration_and_subtext: 8,
  emotional_curve_and_aftertaste: 15,
  cultural_fact_and_adaptation_boundary: 8,
  production_executability: 10,
  originality_and_distinctiveness: 6,
};

function contract(input: Omit<ProfessionalTextTypeContract,
  'schema_version' | 'required_package_fields' | 'hard_gates'
> & { hard_gates?: string[] }): ProfessionalTextTypeContract {
  return {
    schema_version: 'professional-text-type-contract/v1',
    required_package_fields: [...PROFESSIONAL_TEXT_PACKAGE_FIELDS],
    ...input,
    hard_gates: [...COMMON_HARD_GATES, ...(input.hard_gates ?? [])],
  };
}

export const PROFESSIONAL_TEXT_TYPE_CONTRACTS: Record<VideoType, ProfessionalTextTypeContract> = {
  character_story: contract({
    video_type: 'character_story',
    line: '剧情故事线',
    primary_text_form: '人物选择驱动的分场剧本',
    architecture_mode: 'character_relationships',
    required_deliverables: ['人物命题', '关键选择', '关系网', '人物弧', '分场剧本'],
    exclusive_quality_gate: '不能写成年表；选择必须造成代价和变化',
    quality_dimension_weights: DRAMA_WEIGHTS,
    hard_gates: ['人物必须有当下目标、阻力、选择和可见代价'],
    repair_focus: ['把生平摘要改成单一压力事件', '强化关系变化', '让结尾承接选择后的代价'],
  }),
  historical_drama: contract({
    video_type: 'historical_drama',
    line: '剧情故事线',
    primary_text_form: '史实压力驱动的历史分场剧本',
    architecture_mode: 'character_relationships',
    required_deliverables: ['史实压力', '事件因果', '角色立场', '戏剧化边界', '分场剧本'],
    exclusive_quality_gate: '事实和虚构分层；冲突必须来自时代处境',
    quality_dimension_weights: { ...DRAMA_WEIGHTS, cultural_fact_and_adaptation_boundary: 15, emotional_curve_and_aftertaste: 7, originality_and_distinctiveness: 3 },
    hard_gates: ['史实锚点、合理补足和虚构添加必须分层记录'],
    repair_focus: ['补足制度与时代压力', '把宏观背景转成场景行动', '修复事实与虚构边界'],
  }),
  legend_story: contract({
    video_type: 'legend_story',
    line: '剧情故事线',
    primary_text_form: '有版本边界的口述传说完整剧本',
    architecture_mode: 'character_relationships',
    required_deliverables: ['版本说明', '象征意象', '凡人选择', '口述节奏', '完整剧本'],
    exclusive_quality_gate: '不把传说写成史实；象征必须服务人物选择',
    quality_dimension_weights: DRAMA_WEIGHTS,
    hard_gates: ['必须显式标注民间版本、未知点和象征性处理'],
    repair_focus: ['让神异元素推动凡人考验', '建立重复象征意象', '恢复传说口述节奏和边界'],
  }),
  ai_comic_drama: contract({
    video_type: 'ai_comic_drama',
    line: '剧情故事线',
    primary_text_form: '可分格、可配气泡和表情节拍的短剧本',
    architecture_mode: 'character_relationships',
    required_deliverables: ['集钩子', '关系碰撞', '可分格动作', '对白气泡', '表情节拍', '结尾钩子'],
    exclusive_quality_gate: '每格可画；角色和资产连续；对白不能承担全部叙事',
    quality_dimension_weights: AI_COMIC_WEIGHTS,
    hard_gates: ['每场必须能拆成稳定角色、资产和可画动作'],
    repair_focus: ['压缩对白并补反应格', '强化三秒钩子和结尾追看动作', '修复角色、道具和场景连续性'],
  }),
  children_story: contract({
    video_type: 'children_story',
    line: '剧情故事线',
    primary_text_form: '适龄、温和冲突和重复母题的儿童动画剧本',
    architecture_mode: 'character_relationships',
    required_deliverables: ['年龄段', '温和冲突', '重复母题', '情绪学习', '亲师提示'],
    exclusive_quality_gate: '儿童可理解；不残酷、不恐吓、不把说教当情节',
    quality_dimension_weights: { ...DRAMA_WEIGHTS, creative_brief_and_audience_promise: 10, cultural_fact_and_adaptation_boundary: 8 },
    hard_gates: ['必须标明年龄段并通过儿童安全与理解门槛'],
    repair_focus: ['简化冲突与词汇', '用行动呈现情绪学习', '把说教改成重复母题和温暖反馈'],
  }),
  culture_promo: contract({
    video_type: 'culture_promo',
    line: '宣传传播线',
    primary_text_form: '传播命题驱动的旁白与导演文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['传播命题', '视觉符号', '信息曲线', '旁白', '行动召唤'],
    exclusive_quality_gate: '不能只有赞美；文化细节必须承担叙事功能',
    quality_dimension_weights: PROMO_WEIGHTS,
    hard_gates: ['传播主张必须由可核验文化细节和可拍画面支撑'],
    repair_focus: ['把赞美和口号改成具体对象', '建立视觉符号的重复与变化', '让行动召唤承接观众承诺'],
  }),
  heritage_promo: contract({
    video_type: 'heritage_promo',
    line: '宣传传播线',
    primary_text_form: '材料、工具和工序驱动的非遗导演文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['材料', '工具', '工序', '手部动作', '传承压力', '当代连接'],
    exclusive_quality_gate: '工序可拍；授权和危险操作边界清楚',
    quality_dimension_weights: { ...PROMO_WEIGHTS, cultural_fact_and_adaptation_boundary: 13, production_executability: 12, emotional_curve_and_aftertaste: 5, originality_and_distinctiveness: 3 },
    hard_gates: ['工序顺序、授权、禁忌和危险操作必须可核验'],
    repair_focus: ['补材料工具和手部动词', '建立师徒或传承压力', '补足授权与危险操作提示'],
  }),
  city_brand_promo: contract({
    video_type: 'city_brand_promo',
    line: '宣传传播线',
    primary_text_form: '人物视角和空间路线驱动的城市品牌片文本',
    architecture_mode: 'spatial_route',
    required_deliverables: ['城市主张', '人物视角', '空间路线', '城市证据', '品牌落点'],
    exclusive_quality_gate: '避免城市宣传套话；地理、生活和人物必须真实关联',
    quality_dimension_weights: PROMO_WEIGHTS,
    hard_gates: ['城市主张必须有真实空间、生活方式和人物证据'],
    repair_focus: ['删除通用城市套话', '用人物行动连接空间路线', '让品牌落点来自前文证据'],
  }),
  social_short: contract({
    video_type: 'social_short',
    line: '宣传传播线',
    primary_text_form: '竖屏钩子、节拍和字幕一体的社交短视频文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['三秒钩子', '节拍表', '反差', '字幕', '竖屏画面', '互动问题'],
    exclusive_quality_gate: '60 至 90 秒内持续有新信息；事实边界不能被钩子牺牲',
    quality_dimension_weights: { ...PROMO_WEIGHTS, structure_causality_and_pacing: 17, dialogue_narration_and_subtext: 13, character_agency_and_relationship_change: 3, emotional_curve_and_aftertaste: 8, originality_and_distinctiveness: 4 },
    hard_gates: ['强钩子不得扭曲事实、身份、地域或机构口径'],
    repair_focus: ['重写前三秒观看理由', '压缩无新信息节拍', '让字幕、画面和旁白分工'],
  }),
  documentary_short: contract({
    video_type: 'documentary_short',
    line: '非虚构与知识线',
    primary_text_form: '现实现场和证据发现驱动的微纪录文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['核心问题', '现实现场', '采访角色', '史料线索', 'B-roll', '再现边界'],
    exclusive_quality_gate: '不虚构采访或现场；旁白克制；证据推动发现',
    quality_dimension_weights: NONFICTION_WEIGHTS,
    hard_gates: ['不得伪造采访、现场、文献来源或历史再现证据'],
    repair_focus: ['从现实现场提出问题', '用证据而非旁白推动发现', '标注采访、史料和再现边界'],
  }),
  explainer_video: contract({
    video_type: 'explainer_video',
    line: '非虚构与知识线',
    primary_text_form: '问题、概念、例子和视觉比喻驱动的解释文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['问题', '概念', '例子', '视觉比喻', '误区', '总结'],
    exclusive_quality_gate: '一段只讲一个核心概念；画面能解释而非装饰',
    quality_dimension_weights: NONFICTION_WEIGHTS,
    hard_gates: ['概念、例子和视觉比喻不得造成事实性误导'],
    repair_focus: ['拆分一段多概念', '补可视化因果或比喻', '增加误区辨析和可复述结论'],
  }),
  lecture_video: contract({
    video_type: 'lecture_video',
    line: '非虚构与知识线',
    primary_text_form: '立论、论证、反方和结论驱动的讲演文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['立论', '论证', '案例', '反方', '修辞转场', '行动结论'],
    exclusive_quality_gate: '论点可验证；不是资料罗列或口号堆叠',
    quality_dimension_weights: NONFICTION_WEIGHTS,
    hard_gates: ['核心论点和关键案例必须可验证并回应合理反方'],
    repair_focus: ['建立论点与证据链', '补反方和回应', '把资料罗列改成有目的的修辞转场'],
  }),
  education_training: contract({
    video_type: 'education_training',
    line: '非虚构与知识线',
    primary_text_form: '目标、示范、练习和评估闭环的培训文本',
    architecture_mode: 'information_architecture',
    required_deliverables: ['学习目标', '知识步骤', '案例', '练习', '评估', '复盘'],
    exclusive_quality_gate: '能教会和检验；练习与目标对应',
    quality_dimension_weights: { ...NONFICTION_WEIGHTS, creative_brief_and_audience_promise: 12, structure_causality_and_pacing: 18, cultural_fact_and_adaptation_boundary: 13, emotional_curve_and_aftertaste: 3, production_executability: 14, originality_and_distinctiveness: 2 },
    hard_gates: ['学习目标、练习和评估必须一一对应'],
    repair_focus: ['把目标改成可观察能力', '补示范与分步练习', '让评估验证学习目标'],
  }),
  scene_short: contract({
    video_type: 'scene_short',
    line: '空间与意境线',
    primary_text_form: '空间路线、事件触发和声音转场驱动的场景文本',
    architecture_mode: 'spatial_route',
    required_deliverables: ['空间路线', '人物或事件触发', '镜头行动', '声音', '转场'],
    exclusive_quality_gate: '空间必须发生变化或发现，不能只是景点介绍',
    quality_dimension_weights: SPATIAL_WEIGHTS,
    hard_gates: ['每个空间节点必须发生行动、发现或时间变化'],
    repair_focus: ['建立清晰空间路线', '加入触发行动或发现', '用声音和转场连接时间层'],
  }),
  landscape_mood: contract({
    video_type: 'landscape_mood',
    line: '空间与意境线',
    primary_text_form: '时间、构图、自然声音和极简文案驱动的意境文本',
    architecture_mode: 'visual_mood',
    required_deliverables: ['情绪命题', '时间变化', '构图节奏', '自然声音', '极简文案'],
    exclusive_quality_gate: '情绪由视听建立；文案不能压过画面',
    quality_dimension_weights: SPATIAL_WEIGHTS,
    hard_gates: ['去掉旁白后仍必须看得出时间、空间和情绪结构'],
    repair_focus: ['减少知识解释和口号', '加强光影、天气和自然声音变化', '把文案压到最少必要密度'],
  }),
};

export function getProfessionalTextTypeContract(videoType: VideoType): ProfessionalTextTypeContract {
  return PROFESSIONAL_TEXT_TYPE_CONTRACTS[videoType];
}
