import type { ProfessionalTextPackage, ResearchAndEvidenceDossier, StoryGenerateResult, SupportedDuration, TruthMode } from '@shared/types.js';
import { createProfessionalTextPackageSkeleton } from './professional-text-package-service.js';
import { evaluateCulturePromoProfessionalText, type CulturePromoProfessionalEvidence } from './professional-culture-promo-quality-service.js';

export interface CulturePromoProfessionalPipelineInput { story: StoryGenerateResult; target_audience: string; platform: string; target_duration?: SupportedDuration; communication_goal: string; production_goal: string; audience_promise: string; truth_mode?: TruthMode; research: ResearchAndEvidenceDossier; promo_evidence: CulturePromoProfessionalEvidence; now?: string; }
export function buildCulturePromoProfessionalTextPackage(input: CulturePromoProfessionalPipelineInput): ProfessionalTextPackage {
  if (input.story.video_type !== 'culture_promo') throw new Error('culture_promo professional pipeline requires a culture_promo source');
  const { story, promo_evidence: e } = input; const now = input.now ?? new Date().toISOString(); const duration = input.target_duration ?? story.story_blueprint?.target_duration ?? '3分钟';
  const pkg = createProfessionalTextPackageSkeleton({ video_type: 'culture_promo', package_id: `${story.storyId}--professional-text`, story_id: story.storyId, project_id: story.project_id, target_duration: duration, target_audience: input.target_audience, platform: input.platform, communication_goal: input.communication_goal, truth_mode: input.truth_mode ?? story.truth_mode, now });
  const byStatus = (status: string) => input.research.evidence_items.filter(item => item.status === status).map(item => item.claim);
  pkg.creative_brief = { target_audience: input.target_audience, platform: input.platform, target_duration: duration, communication_goal: input.communication_goal, production_goal: input.production_goal, budget_assumptions: [], delivery_constraints: ['旁白不重复画面', '传播主张必须有文化证据'] };
  pkg.research_and_evidence_dossier = input.research; pkg.audience_promise = input.audience_promise; pkg.premise_or_core_question = e.communication_proposition; pkg.theme_statement = e.audience_takeaway;
  pkg.truth_and_adaptation_contract = { truth_mode: input.truth_mode ?? story.truth_mode ?? 'inspired_by_material', verified_facts: byStatus('verified_fact'), plausible_dramatizations: byStatus('plausible_dramatization'), fictional_additions: byStatus('fictional_addition'), unknown_or_forbidden_claims: [...input.research.unknowns], required_disclaimers: story.creation_contract?.required_disclaimers ?? ['诗化旁白和画面连接为宣传创作，文化事实以来源为准。'] };
  pkg.relationship_or_information_architecture = { mode: 'information_architecture', nodes: e.information_curve.map(beat => ({ node_id: `promo-info-${beat.scene_id}`, label: beat.new_information, role: beat.audience_effect })), links: e.information_curve.slice(1).map((beat, index) => ({ from: `promo-info-${e.information_curve[index].scene_id}`, to: `promo-info-${beat.scene_id}`, relationship: '信息递进' })) };
  pkg.structure_outline = { structure_name: 'symbol-to-action-promo', opening: e.visual_symbols[0]?.label ?? story.scene_breakdown[0]?.plot ?? '', development: e.information_curve.slice(1, -1).map(beat => beat.new_information), climax_or_key_turn: e.modern_connection, ending: `${e.slogan_or_key_sentence}；${e.call_to_action}` };
  pkg.sequence_beats = story.scene_breakdown.map((scene, index) => ({ beat_id: `promo-beat-${index + 1}`, order: index + 1, title: scene.title, purpose: scene.dramatic_function, visible_action: scene.key_action, conflict_discovery_or_instruction: e.information_curve.find(beat => beat.scene_id === Number(scene.scene_id))?.new_information ?? scene.plot, emotional_or_information_turn: e.scene_turns[String(scene.scene_id)] ?? '', evidence_ids: e.proof_points.flatMap(point => point.evidence_ids) }));
  pkg.scene_breakdown = story.scene_breakdown; pkg.full_text = story.full_text;
  pkg.dialogue_or_narration_pass = { mode: 'narration', voice_rules: e.voiceover_visual_division, polished_text: story.scene_breakdown.map(scene => scene.dialogue_or_narration).filter(Boolean).join('\n'), unresolved_issues: [] };
  pkg.director_text_plan = { visual_strategy: `以${e.visual_symbols.map(symbol => symbol.label).join('、')}重复并变化，先见符号再理解意义。`, sound_strategy: '旁白只提供画面没有的信息，材料声、空间声和人物动作承担质感。', rhythm_strategy: '符号引入、文化证据、具体过程、当代连接、行动召唤。', sequences: story.scene_breakdown.map(scene => ({ sequence_id: `promo-sequence-${scene.scene_id}`, scene_ids: [scene.scene_id], blocking_and_visible_action: scene.key_action, camera_and_transition_intent: scene.camera_suggestion, sound_intent: scene.dialogue_or_narration ?? '环境声与动作声。', production_constraints: e.visual_symbols.filter(symbol => symbol.scene_ids.includes(Number(scene.scene_id))).map(symbol => `${symbol.label}:${symbol.meaning}`) })) };
  pkg.continuity_ledger = { items: e.visual_symbols.map(symbol => ({ continuity_id: `promo-${symbol.symbol_id}`, category: 'prop' as const, rule: `${symbol.label}：${symbol.meaning}`, applies_to_scene_ids: symbol.scene_ids, evidence_ids: e.proof_points.flatMap(point => point.evidence_ids) })), unresolved_conflicts: [] };
  pkg.delivery_text_package = { script_text: story.full_text, scene_units: story.scene_breakdown.map(scene => ({ scene_id: scene.scene_id, script_text: scene.dialogue_or_narration ?? scene.plot, visual_action: scene.key_action, camera_intent: scene.camera_suggestion, sound_intent: '旁白与现场声分层。', continuity_notes: e.visual_symbols.filter(symbol => symbol.scene_ids.includes(Number(scene.scene_id))).map(symbol => symbol.label), evidence_boundary_notes: e.proof_points.map(point => point.claim) })), gears_handoff_notes: ['视觉符号和文化证据必须显式传递。'], seedance_handoff_notes: ['不得用纯氛围镜头替代已登记文化细节。'], validation_notes: [] };
  const evaluation = evaluateCulturePromoProfessionalText({ package: pkg, promo_evidence: e }); pkg.quality_report = evaluation.quality_report; pkg.coverage_report = evaluation.coverage_report; pkg.status = pkg.quality_report.hard_gate_failures.length ? 'revision_required' : 'in_review'; return pkg;
}
