import type { ProfessionalTextPackage, ProfessionalTextPackageField } from '@shared/types.js';
import { culturePromoHardGateRepair, evaluateCulturePromoProfessionalText, type CulturePromoProfessionalEvidence } from './professional-culture-promo-quality-service.js';
const issueId = (failure: string) => failure.split(':', 1)[0]?.trim() || 'unknown_issue';
export function buildCulturePromoRevisionPlan(pkg: ProfessionalTextPackage) {
  if (pkg.video_type !== 'culture_promo') throw new Error('culture_promo revision plan requires a culture_promo package');
  const human = new Set(['brief_missing', 'proof_point_missing', 'truth_boundary_missing']);
  const actions = pkg.quality_report.hard_gate_failures.map((failure, index) => { const issue = issueId(failure); return { action_id: `promo-revision-${index + 1}`, issue_id: issue, instruction: culturePromoHardGateRepair(issue) ?? '按 Coverage 修订宣传文本。', target_sections: (human.has(issue) ? ['truth_and_adaptation_contract', 'continuity_ledger'] : ['structure_outline', 'sequence_beats', 'full_text']) as ProfessionalTextPackageField[], repair_mode: human.has(issue) ? 'human_evidence_required' as const : 'model_rewrite_required' as const, rebuild_derived_sections: ['director_text_plan', 'delivery_text_package'] as ProfessionalTextPackageField[] }; });
  return { schema_version: 'professional-text-revision-plan/v1' as const, package_id: pkg.package_id, video_type: 'culture_promo' as const, action_count: actions.length, deterministic_action_count: 0, model_rewrite_action_count: actions.filter(a => a.repair_mode === 'model_rewrite_required').length, human_evidence_action_count: actions.filter(a => a.repair_mode === 'human_evidence_required').length, actions, professional_passed: false as const };
}
export function rebuildCulturePromoDerivedText(input: { package: ProfessionalTextPackage; promo_evidence: CulturePromoProfessionalEvidence; now?: string }) {
  const pkg = structuredClone(input.package); if (pkg.video_type !== 'culture_promo') throw new Error('culture_promo derived rebuild requires culture_promo'); const rebuilt: ProfessionalTextPackageField[] = [];
  if (pkg.sequence_beats.length !== pkg.scene_breakdown.length) { pkg.sequence_beats = pkg.scene_breakdown.map((scene, index) => ({ beat_id: `promo-rebuild-${index + 1}`, order: index + 1, title: scene.title, purpose: scene.dramatic_function, visible_action: scene.key_action, conflict_discovery_or_instruction: scene.plot, emotional_or_information_turn: input.promo_evidence.scene_turns[String(scene.scene_id)] ?? '', evidence_ids: [] })); rebuilt.push('sequence_beats'); }
  if (pkg.delivery_text_package.scene_units.length !== pkg.scene_breakdown.length) { pkg.delivery_text_package.scene_units = pkg.scene_breakdown.map(scene => ({ scene_id: scene.scene_id, script_text: scene.dialogue_or_narration ?? scene.plot, visual_action: scene.key_action, camera_intent: scene.camera_suggestion, sound_intent: '旁白与现场声分层。', continuity_notes: [], evidence_boundary_notes: [] })); rebuilt.push('delivery_text_package'); }
  const evaluation = evaluateCulturePromoProfessionalText({ package: pkg, promo_evidence: input.promo_evidence }); pkg.quality_report = evaluation.quality_report; pkg.coverage_report = evaluation.coverage_report; pkg.status = pkg.quality_report.hard_gate_failures.length ? 'revision_required' : 'in_review'; pkg.updated_at = input.now ?? new Date().toISOString(); if (rebuilt.length) pkg.revision_trace.push({ revision_id: `promo-rebuild-${pkg.revision_trace.length + 1}`, created_at: pkg.updated_at, source: 'agent', reason: '重建宣传片派生文本。', changed_sections: rebuilt, resolved_issue_ids: [], remaining_issues: pkg.quality_report.hard_gate_failures.map(issueId) }); return { package: pkg, rebuilt_sections: rebuilt };
}
