import { describe, expect, it } from 'vitest';
import { parseFullEntry } from './markdown.js';

describe('parseFullEntry', () => {
  it('does not read asset sections from the next markdown entry', () => {
    const content = [
      '# 湖南',
      '',
      '## 已整理条目',
      '',
      '---',
      '',
      '## 前一条',
      '',
      '- **省份**：湖南',
      '- **地区**：测试',
      '- **类型**：地方掌故',
      '',
      '### 简介',
      '',
      '前一条简介。',
      '',
      '### 故事梗概',
      '',
      '前一条故事。',
      '',
      '### 文化意义',
      '',
      '前一条意义。',
      '',
      '### 相关地点',
      '',
      '- 前地点：前一条地点',
      '',
      '### 关键词',
      '',
      '前一条',
      '',
      '### 来源',
      '',
      '- 前源（B级）',
      '',
      '### 可信度',
      '',
      '基本可靠',
      '',
      '### 核实方法',
      '',
      '前一条核实。',
      '',
      '### 待核实点',
      '',
      '- 前一条待核',
      '',
      '---',
      '',
      '### 邵阳',
      '',
      '---',
      '',
      '## 后一条',
      '',
      '- **省份**：湖南',
      '- **地区**：测试',
      '- **类型**：非遗',
      '',
      '### 简介',
      '',
      '后一条简介。',
      '',
      '### 故事梗概',
      '',
      '后一条故事。',
      '',
      '### 文化意义',
      '',
      '后一条意义。',
      '',
      '### 相关地点',
      '',
      '- 后地点：后一条地点',
      '',
      '### 关键词',
      '',
      '后一条',
      '',
      '### 来源',
      '',
      '- 后源（B级）',
      '',
      '### 可信度',
      '',
      '基本可靠',
      '',
      '### 核实方法',
      '',
      '后一条核实。',
      '',
      '### 待核实点',
      '',
      '- 后一条待核',
      '',
      '### 人物',
      '',
      '- 后人物',
      '',
      '### 场景',
      '',
      '- 后场景',
      '',
      '### 人物随身道具',
      '',
      '- 后道具',
      '',
      '### 场景陈设',
      '',
      '- 后陈设',
      '',
    ].join('\n');

    const first = parseFullEntry(content, '前一条');
    const second = parseFullEntry(content, '后一条');

    expect(first?.sources).toEqual(['前源（B级）']);
    expect(first?.asset_split).toBeUndefined();
    expect(second?.asset_split?.characters).toEqual(['后人物']);
    expect(second?.asset_split?.scenes).toEqual(['后场景']);
    expect(second?.asset_split?.character_props).toEqual(['后道具']);
    expect(second?.asset_split?.scene_props).toEqual(['后陈设']);
  });
});
