import { CultureEntry } from '../types.js';

export function formatEntry(entry: CultureEntry): string {
  const lines: string[] = [
    '---',
    '',
    `## ${entry.name}`,
    '',
    `- **省份**：${entry.province}`,
    `- **地区**：${entry.region}`,
    `- **类型**：${entry.type}`,
    '',
    '### 简介',
    '',
    entry.summary,
    '',
    '### 故事梗概',
    '',
    entry.story,
    '',
    '### 文化意义',
    '',
    entry.culturalSignificance,
    '',
    '### 相关地点',
    '',
    ...entry.relatedLocations.map(loc => `- ${loc.name}：${loc.description}`),
    '',
    '### 关键词',
    '',
    entry.keywords.join('、'),
    '',
    '### 来源',
    '',
    ...entry.sources.map(s => `- ${s}`),
    '',
    '### 可信度',
    '',
    entry.credibility,
    '',
    '### 核实方法',
    '',
    entry.verificationMethod || '未标注',
    '',
    '### 待核实点',
    '',
    ...entry.unverifiedPoints.map(p => `- ${p}`),
    '',
    '---',
  ];
  return lines.join('\n');
}