<template>
  <section class="signature-page">
    <header class="hero"><div><p class="eyebrow">STORY AGENT · STAGE 6 · SIGNED EXIT REVIEW</p><h2>退出复核 Ed25519 签名验证</h2><p>验证三角色外部签名、固定信任策略、当前退出审计哈希和真实项目绑定；系统不生成签名。</p></div><nav><RouterLink to="/story/stage6-exit-audit">退出审计</RouterLink><RouterLink to="/story/stage6-operations">Stage 6 总控</RouterLink></nav></header>
    <div class="truth-lock"><strong>验证签名 ≠ 创建签名</strong><span>Trust policy 独立于 attestation；验证通过也不自动落盘 Stage 6 退出记录，更不等于专业通过。</span></div>
    <p v-if="errorMessage" class="error-banner">{{ errorMessage }}</p>

    <section v-if="workspace" class="trust-bar"><div><span>Trust policy</span><strong>{{ workspace.trust_policy.policy_id }}</strong></div><div><span>状态</span><strong>{{ workspace.trust_policy.status }}</strong></div><div><span>Trusted signers</span><strong>{{ workspace.trust_policy.trusted_signer_count }} / {{ workspace.trust_policy.required_role_count }}</strong></div><label>项目<select v-model="selectedBenchmarkId"><option v-for="project in workspace.projects" :key="project.benchmark_id" :value="project.benchmark_id">{{ project.source_entry }} · candidate {{ project.stage6_exit_candidate?'yes':'no' }}</option></select></label><button :disabled="loading" @click="loadTemplate">生成绑定模板</button><button class="primary" :disabled="loading||!editorText" @click="runInspection">{{ loading?'验证中…':'验证外部签名' }}</button></section>

    <section class="workspace-grid">
      <article class="editor-card"><header><div><p class="eyebrow">ATTESTATION JSON</p><h3>外部签署记录</h3></div><span>仅内存</span></header><div class="toolbar"><label>导入 JSON<input type="file" accept=".json,application/json" @change="importFile"/></label><button @click="copyJson">复制 JSON</button><span>{{ copyMessage }}</span></div><textarea v-model="editorText" aria-label="Stage 6 exit review attestation JSON" spellcheck="false"/><footer><span>{{ editorText.length.toLocaleString() }} 字符</span><b>不签署 · 不导入</b></footer></article>

      <article class="result-card"><header><div><p class="eyebrow">VERIFICATION RESULT</p><h3>信任、绑定与密码学验证</h3></div><b :class="inspection?.signature_verification_ready?'ready':'blocked'">{{ inspection?.signature_verification_ready?'VERIFIED FOR IMPORT':'BLOCKED' }}</b></header>
        <div v-if="inspection" class="metrics"><div><span>Schema</span><strong>{{ inspection.checks.attestation_schema_valid?'合法':'失败' }}</strong></div><div><span>退出候选</span><strong>{{ inspection.checks.stage6_exit_candidate_reverified?'是':'否' }}</strong></div><div><span>已验签</span><strong>{{ inspection.signature_summary.cryptographically_verified_signature_count }}/3</strong></div><div><span>专业通过</span><strong>0</strong></div></div>
        <div v-if="inspection" class="binding-panel"><span>Benchmark <b>{{ inspection.expected_binding.benchmark_id }}</b></span><span>Real project <b>{{ inspection.expected_binding.real_project_id||'未绑定' }}</b></span><span>Audit binding <code>{{ shortHash(inspection.expected_binding.exit_audit_binding_sha256) }}</code></span><span>Attestation payload <code>{{ inspection.canonical_attestation_payload_sha256?shortHash(inspection.canonical_attestation_payload_sha256):'Schema 合法后生成' }}</code></span></div>
        <section v-if="inspection" class="roles"><article><span>编剧 / 编辑</span><strong>{{ inspection.signature_summary.writer_editor_signature_count }}</strong></article><article><span>类型 / 导演</span><strong>{{ inspection.signature_summary.director_signature_count }}</strong></article><article><span>事实 / 文化</span><strong>{{ inspection.signature_summary.fact_culture_reviewer_signature_count }}</strong></article><article><span>Trusted</span><strong>{{ inspection.signature_summary.trusted_signer_count }}</strong></article></section>
        <section v-if="inspection" class="checks"><h4>退出复核签名门禁</h4><div><span v-for="(passed,key) in inspection.checks" :key="key" :class="passed?'ok':'fail'">{{ passed?'✓':'×' }} {{ checkLabel(key) }}</span></div></section>
        <section v-if="inspection?.issues.length" class="issues"><h4>问题 {{ inspection.issues.length }} 项</h4><article v-for="(item,index) in inspection.issues" :key="`${item.code}-${index}`" :class="item.blocking?'blocking':'warning'"><header><b>{{ item.gate.toUpperCase() }}</b><code>{{ item.code }}</code></header><span>{{ item.path||'root' }}</span><p>{{ item.message }}</p></article></section>
        <div class="safety-grid"><span>Signature created <b>否</b></span><span>Attestation persisted <b>否</b></span><span>Exit record persisted <b>否</b></span><span>Execution started <b>否</b></span><span>Professional passed <b>否</b></span></div>
      </article>
    </section>
  </section>
</template>

<script setup lang="ts">
import { onMounted,ref } from 'vue'
import type { Stage6ExitReviewSignatureInspectionResult,Stage6ExitReviewSignatureInspectorWorkspace } from '@shared/types'
import { getStage6ExitReviewSignatureInspector,inspectStage6ExitReviewSignature } from '../api/stage6-revisions'
const workspace=ref<Stage6ExitReviewSignatureInspectorWorkspace|null>(null),inspection=ref<Stage6ExitReviewSignatureInspectionResult|null>(null),selectedBenchmarkId=ref(''),editorText=ref(''),loading=ref(false),errorMessage=ref(''),copyMessage=ref('')
const labels:Record<string,string>={request_valid:'检查请求',json_valid:'JSON 可解析',attestation_schema_valid:'Attestation schema',trust_policy_schema_valid:'Trust policy schema',trust_policy_active:'Trust policy 已激活',stage6_exit_candidate_reverified:'退出候选重验',benchmark_binding_valid:'Benchmark 绑定',real_project_binding_valid:'真实项目绑定',exit_audit_binding_valid:'退出审计哈希绑定',approval_decision_valid:'批准决定',required_roles_signed:'三角色签名齐全',trusted_signer_bindings_valid:'Signer 与信任策略绑定',signed_payload_digests_valid:'签名 Payload Hash',cryptographic_signatures_valid:'Ed25519 验签',signature_timestamps_valid:'签名时间'}
onMounted(loadTemplate)
async function loadTemplate(){loading.value=true;errorMessage.value='';const response=await getStage6ExitReviewSignatureInspector(selectedBenchmarkId.value);loading.value=false;if(!response.ok||!response.data){errorMessage.value=response.error?.message??'签名模板加载失败';return}workspace.value=response.data;selectedBenchmarkId.value=response.data.selected_benchmark_id;editorText.value=response.data.template_raw_json;inspection.value=response.data.template_inspection}
async function runInspection(){loading.value=true;errorMessage.value='';const response=await inspectStage6ExitReviewSignature({raw_json:editorText.value,expected_benchmark_id:selectedBenchmarkId.value});loading.value=false;if(!response.ok||!response.data){errorMessage.value=response.error?.message??'退出复核签名验证失败';return}inspection.value=response.data}
async function importFile(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{editorText.value=await file.text();errorMessage.value=''}catch(error){errorMessage.value=`导入失败：${(error as Error).message}`}finally{input.value=''}}
async function copyJson(){try{await navigator.clipboard.writeText(editorText.value);copyMessage.value='已复制'}catch{copyMessage.value='复制未授权'}window.setTimeout(()=>copyMessage.value='',1600)}
function checkLabel(value:string){return labels[value]??value} function shortHash(value:string){return value?`${value.slice(0,10)}…${value.slice(-6)}`:'—'}
</script>

<style scoped>
.signature-page{min-height:100%;padding:28px;color:#eceef1;background:radial-gradient(circle at 88% 0%,#3b475a,#192330 40%,#090e15 100%)}.hero{max-width:1440px;margin:0 auto 17px;display:flex;align-items:flex-end;justify-content:space-between;gap:24px}.hero h2{margin:4px 0 8px;font-size:clamp(30px,4vw,48px);letter-spacing:-.04em}.hero p{margin:0;max-width:900px;color:#aab2bd}.hero nav{display:flex;gap:8px}.hero a,.trust-bar button,.toolbar button,.toolbar label{padding:9px 13px;border:1px solid #53647c;border-radius:9px;color:#e3e8ef;background:#242e3d;text-decoration:none;cursor:pointer;font:inherit}.eyebrow{color:#a8bee8!important;font-size:11px;font-weight:800;letter-spacing:.17em}.truth-lock{max-width:1440px;margin:0 auto 15px;padding:14px 16px;display:flex;gap:14px;border:1px solid #886835;border-radius:12px;color:#efd39e;background:#302515}.truth-lock span{color:#c5ac7e}.error-banner{max-width:1440px;margin:0 auto 13px;padding:11px;border-radius:9px;color:#ffb0be;background:#481d2a}.trust-bar{max-width:1440px;margin:0 auto 15px;padding:11px;display:flex;align-items:flex-end;gap:8px;border:1px solid #41516a;border-radius:11px;background:#131b28}.trust-bar>div{min-width:120px}.trust-bar span{display:block;color:#8490a2;font-size:9px}.trust-bar strong{font-size:11px}.trust-bar label{flex:1;color:#8995a7;font-size:9px}.trust-bar select{width:100%;margin-top:4px;padding:8px;border:1px solid #52627b;border-radius:7px;color:#e2e7ee;background:#0c121c}.trust-bar .primary{background:#3a5279;border-color:#819fd2}.trust-bar button:disabled{opacity:.5}
.workspace-grid{max-width:1440px;margin:auto;display:grid;grid-template-columns:minmax(420px,.86fr) minmax(570px,1.14fr);gap:15px;align-items:start}.editor-card,.result-card{overflow:hidden;border:1px solid #42516a;border-radius:13px;background:rgba(17,24,35,.96)}.editor-card{position:sticky;top:15px}.editor-card>header,.result-card>header{padding:15px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #344156}.editor-card h3,.result-card h3{margin:3px 0 0}.editor-card header span{color:#7f8a9b;font:10px ui-monospace,monospace}.result-card header>b{font-size:10px;letter-spacing:.07em}.ready{color:#74dbc2}.blocked{color:#ff92a9}.toolbar{padding:10px 13px;display:flex;align-items:center;gap:7px}.toolbar input{display:none}.toolbar span{color:#8490a1;font-size:10px}textarea{width:100%;min-height:650px;padding:16px;box-sizing:border-box;resize:vertical;border:0;border-block:1px solid #2d394c;outline:0;color:#d7dce5;background:#080d14;font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.editor-card footer{padding:10px 13px;display:flex;justify-content:space-between;color:#7e899a;font-size:10px}.editor-card footer b{color:#aac0ec}
.metrics{margin:14px;display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.metrics div{padding:9px;border-radius:7px;background:#202a39}.metrics span{display:block;color:#8793a4;font-size:9px}.metrics strong{font-size:15px}.metrics div:last-child strong{color:#ff91a9}.binding-panel,.safety-grid{margin:0 14px 12px;display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.binding-panel span,.safety-grid span{padding:8px;border-radius:7px;color:#8390a1;background:#1c2533;font-size:9px}.binding-panel b,.binding-panel code,.safety-grid b{float:right;max-width:65%;color:#d5dbe5;overflow-wrap:anywhere}.safety-grid b{color:#ff94aa}.roles{margin:0 14px 12px;display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.roles article{padding:8px;border-radius:7px;background:#202a38}.roles span{display:block;color:#8793a3;font-size:8px}.roles strong{font-size:17px}.checks,.issues{margin:0 14px 13px}.checks h4,.issues h4{margin:0 0 7px}.checks>div{display:grid;grid-template-columns:repeat(2,1fr);gap:5px}.checks span{padding:7px;border-radius:6px;font-size:9px}.ok{color:#74d7c0;background:#14362f}.fail{color:#ee96aa;background:#361b27}.issues>article{margin:5px 0;padding:8px;border:1px solid #4e3e49;border-radius:7px;background:#261a21}.issues>article.warning{border-color:#68532e;background:#292114}.issues article header{display:flex;gap:7px}.issues article b{color:#e99aaf;font-size:8px}.issues .warning b{color:#dfbc71}.issues code{color:#c5b8c0;font-size:9px}.issues article>span{display:block;margin-top:3px;color:#8c7f87;font-size:9px}.issues p{margin:2px 0 0;color:#bdb2b8;font-size:10px}
@media(max-width:1100px){.trust-bar{flex-wrap:wrap}.workspace-grid{grid-template-columns:1fr}.editor-card{position:static}textarea{min-height:450px}}@media(max-width:720px){.signature-page{padding:18px 12px}.hero,.truth-lock,.trust-bar{align-items:flex-start;flex-direction:column}.trust-bar label{width:100%}.metrics,.roles{grid-template-columns:repeat(2,1fr)}.checks>div,.binding-panel,.safety-grid{grid-template-columns:1fr}}
</style>
