<template>
  <section class="review-page">
    <header class="hero"><div><p class="eyebrow">STORY AGENT · STAGE 6 · HUMAN TABLE READ</p><h2>真人桌读证据与签署前预检</h2><p>核对三角色实名身份、真实项目、轮次、桌读 session、反馈结构和提交时间；系统不创建签名。</p></div><nav><RouterLink to="/story/stage6-operations">Stage 6 总控</RouterLink><RouterLink to="/story/stage6-revisions">修订工作台</RouterLink></nav></header>
    <div class="truth-lock"><strong>签署前 Ready ≠ 已签署</strong><span>检查结果不落盘、不关闭意见、不授予真人桌读信用；自报 signature、human credit 或 professional pass 均不被接受。</span></div>
    <p v-if="errorMessage" class="error-banner">{{ errorMessage }}</p>

    <section class="selector-bar">
      <label>项目<select v-model="selectedBenchmarkId"><option v-for="project in workspace?.projects ?? []" :key="project.benchmark_id" :value="project.benchmark_id">{{ project.source_entry }} · {{ project.readiness_status }}</option></select></label>
      <label>轮次<select v-model.number="selectedRound"><option :value="1">Round 1</option><option :value="2">Round 2</option></select></label>
      <button :disabled="loading" @click="loadTemplate">生成绑定模板</button>
      <button class="primary" :disabled="loading || !editorText" @click="runInspection">{{ loading ? '检查中…' : '运行签署前预检' }}</button>
    </section>

    <section class="workspace-grid">
      <article class="editor-card"><header><div><p class="eyebrow">TABLE READ JSON</p><h3>桌读证据原文</h3></div><span>仅内存</span></header><div class="toolbar"><label>导入 JSON<input type="file" accept=".json,application/json" @change="importFile" /></label><button @click="copyJson">复制 JSON</button><span>{{ copyMessage }}</span></div><textarea v-model="editorText" aria-label="Stage 6 table read evidence JSON" spellcheck="false"/><footer><span>{{ editorText.length.toLocaleString() }} 字符</span><b>不签署 · 不落盘</b></footer></article>

      <article class="result-card"><header><div><p class="eyebrow">SIGNATURE PREFLIGHT</p><h3>身份与证据门禁</h3></div><b :class="inspection?.signature_preflight_ready ? 'ready' : 'blocked'">{{ inspection?.signature_preflight_ready ? 'READY TO REQUEST SIGNATURE' : 'BLOCKED' }}</b></header>
        <div v-if="inspection" class="metrics"><div><span>Schema</span><strong>{{ inspection.schema_valid ? '合法' : '失败' }}</strong></div><div><span>反馈</span><strong>{{ inspection.artifact_summary.feedback_count }}</strong></div><div><span>P0 Ready</span><strong>{{ inspection.checks.p0_readiness_reverified ? '是' : '否' }}</strong></div><div><span>真人信用</span><strong>0</strong></div></div>
        <div v-if="inspection" class="identity-grid"><span>Benchmark <b>{{ inspection.expected_binding.benchmark_id || '—' }}</b></span><span>Real Project <b>{{ inspection.expected_binding.real_project_id || '未绑定' }}</b></span><span>Round <b>{{ inspection.expected_binding.round_number }}</b></span><span>Session <b>{{ inspection.expected_binding.session_reference || '未核验' }}</b></span></div>
        <div v-if="inspection" class="hash-panel"><div><span>原 JSON 文件 SHA-256</span><code>{{ inspection.source_file_sha256 || '—' }}</code></div><div><span>Canonical artifact SHA-256</span><code>{{ inspection.canonical_artifact_sha256 || 'Schema 合法后生成' }}</code></div></div>
        <section v-if="inspection" class="role-grid"><article><span>编剧 / 剧本编辑</span><strong>{{ inspection.artifact_summary.writer_editor_feedback_count }}</strong></article><article><span>类型 / 导演</span><strong>{{ inspection.artifact_summary.director_feedback_count }}</strong></article><article><span>事实 / 文化</span><strong>{{ inspection.artifact_summary.fact_culture_reviewer_feedback_count }}</strong></article><article><span>需证据意见</span><strong>{{ inspection.artifact_summary.evidence_required_feedback_count }}</strong></article></section>
        <section v-if="inspection" class="checks"><h4>签署前检查</h4><div><span v-for="(passed,key) in inspection.checks" :key="key" :class="passed?'ok':'fail'">{{ passed?'✓':'×' }} {{ checkLabel(key) }}</span></div></section>
        <section v-if="inspection?.issues.length" class="issues"><h4>问题 {{ inspection.issues.length }} 项</h4><article v-for="(item,index) in inspection.issues" :key="`${item.code}-${index}`" :class="item.blocking?'blocking':'warning'"><header><b>{{ item.gate.toUpperCase() }}</b><code>{{ item.code }}</code></header><span>{{ item.path || 'root' }}</span><p>{{ item.message }}</p></article></section>
        <div class="safety-grid"><span>Input persisted <b>否</b></span><span>State mutated <b>否</b></span><span>Signature created <b>否</b></span><span>Human credit <b>0</b></span><span>Execution started <b>否</b></span><span>Professional passed <b>否</b></span></div>
      </article>
    </section>
  </section>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { Stage6TableReadEvidenceInspectionResult, Stage6TableReadEvidenceInspectorWorkspace } from '@shared/types'
import { getStage6TableReadEvidenceInspector, inspectStage6TableReadEvidence } from '../api/stage6-revisions'
const workspace=ref<Stage6TableReadEvidenceInspectorWorkspace|null>(null),inspection=ref<Stage6TableReadEvidenceInspectionResult|null>(null),selectedBenchmarkId=ref(''),selectedRound=ref<1|2>(1),editorText=ref(''),loading=ref(false),errorMessage=ref(''),copyMessage=ref('')
const labels:Record<string,string>={request_valid:'检查请求',json_valid:'JSON 可解析',artifact_schema_valid:'桌读 Artifact Schema',p0_readiness_reverified:'P0 Readiness 重验',benchmark_binding_valid:'Benchmark 绑定',real_project_binding_valid:'真实项目绑定',round_binding_valid:'轮次绑定',session_reference_valid:'Session 绑定',table_read_schedule_verified:'桌读排期已核验',three_required_roles_present:'三角色意见齐全',reviewer_ids_match_verified_intake:'Reviewer ID 与 P0 一致',feedback_ids_unique:'Feedback ID 唯一',submitted_at_not_before_scheduled_at:'提交时间不早于桌读'}
onMounted(loadTemplate)
async function loadTemplate(){loading.value=true;errorMessage.value='';const response=await getStage6TableReadEvidenceInspector(selectedBenchmarkId.value,selectedRound.value);loading.value=false;if(!response.ok||!response.data){errorMessage.value=response.error?.message??'桌读模板加载失败';return}workspace.value=response.data;selectedBenchmarkId.value=response.data.selected_benchmark_id;selectedRound.value=response.data.selected_round_number;editorText.value=response.data.template_raw_json;inspection.value=response.data.template_inspection}
async function runInspection(){loading.value=true;errorMessage.value='';const response=await inspectStage6TableReadEvidence({raw_json:editorText.value,expected_benchmark_id:selectedBenchmarkId.value,expected_round_number:selectedRound.value});loading.value=false;if(!response.ok||!response.data){errorMessage.value=response.error?.message??'桌读证据检查失败';return}inspection.value=response.data}
async function importFile(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{editorText.value=await file.text();errorMessage.value=''}catch(error){errorMessage.value=`导入失败：${(error as Error).message}`}finally{input.value=''}}
async function copyJson(){try{await navigator.clipboard.writeText(editorText.value);copyMessage.value='已复制'}catch{copyMessage.value='复制未授权'}window.setTimeout(()=>copyMessage.value='',1600)}
function checkLabel(value:string){return labels[value]??value}
</script>

<style scoped>
.review-page{min-height:100%;padding:28px;color:#eeeaf1;background:radial-gradient(circle at 88% 0%,#503342,#251927 40%,#100c12 100%)}.hero{max-width:1440px;margin:0 auto 17px;display:flex;align-items:flex-end;justify-content:space-between;gap:24px}.hero h2{margin:4px 0 8px;font-size:clamp(30px,4vw,48px);letter-spacing:-.04em}.hero p{margin:0;max-width:900px;color:#b4a7ae}.hero nav{display:flex;gap:8px}.hero a,.selector-bar button,.toolbar button,.toolbar label{padding:9px 13px;border:1px solid #705063;border-radius:9px;color:#eadfe5;background:#33222d;text-decoration:none;cursor:pointer;font:inherit}.eyebrow{color:#e0a6c4!important;font-size:11px;font-weight:800;letter-spacing:.17em}.truth-lock{max-width:1440px;margin:0 auto 16px;padding:14px 16px;display:flex;gap:14px;border:1px solid #896733;border-radius:12px;color:#f0d39c;background:#302414}.truth-lock span{color:#c8ad7a}.error-banner{max-width:1440px;margin:0 auto 13px;padding:11px;border-radius:9px;color:#ffb4c2;background:#4b1c2b}.selector-bar{max-width:1440px;margin:0 auto 15px;padding:12px;display:flex;align-items:flex-end;gap:9px;border:1px solid #523b48;border-radius:11px;background:#21161e}.selector-bar label{flex:1;color:#9e8d96;font-size:10px}.selector-bar select{width:100%;margin-top:4px;padding:8px;border:1px solid #624657;border-radius:7px;color:#eadfe5;background:#160f14}.selector-bar .primary{background:#713d59;border-color:#c47c9f}.selector-bar button:disabled{opacity:.5}
.workspace-grid{max-width:1440px;margin:auto;display:grid;grid-template-columns:minmax(420px,.86fr) minmax(570px,1.14fr);gap:15px;align-items:start}.editor-card,.result-card{overflow:hidden;border:1px solid #523a48;border-radius:13px;background:rgba(28,18,25,.96)}.editor-card{position:sticky;top:15px}.editor-card>header,.result-card>header{padding:15px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #422e39}.editor-card h3,.result-card h3{margin:3px 0 0}.editor-card header span{color:#95818c;font:10px ui-monospace,monospace}.result-card header>b{font-size:10px;letter-spacing:.07em}.ready{color:#7ed9c3}.blocked{color:#ff94aa}.toolbar{padding:10px 13px;display:flex;align-items:center;gap:7px}.toolbar input{display:none}.toolbar span{color:#9c8993;font-size:10px}textarea{width:100%;min-height:650px;padding:16px;box-sizing:border-box;resize:vertical;border:0;border-block:1px solid #3c2933;outline:0;color:#dfd2d9;background:#100b0e;font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.editor-card footer{padding:10px 13px;display:flex;justify-content:space-between;color:#95828b;font-size:10px}.editor-card footer b{color:#e3acc7}
.metrics{margin:14px;display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.metrics div{padding:9px;border-radius:7px;background:#2a1c25}.metrics span{display:block;color:#99858f;font-size:9px}.metrics strong{font-size:15px}.metrics div:last-child strong{color:#ff95ab}.identity-grid,.safety-grid{margin:0 14px 12px;display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.identity-grid span,.safety-grid span{padding:8px;border-radius:7px;color:#96828c;background:#261922;font-size:9px}.identity-grid b,.safety-grid b{float:right;max-width:65%;color:#e0d2d9;overflow-wrap:anywhere}.safety-grid b{color:#ff96ab}.hash-panel{margin:0 14px 12px;padding:10px;border:1px solid #5a4050;border-radius:9px;background:#160f14}.hash-panel div+div{margin-top:7px}.hash-panel span{display:block;color:#94818a;font-size:9px}.hash-panel code{display:block;color:#ddb5c8;overflow-wrap:anywhere;font-size:10px}.role-grid{margin:0 14px 12px;display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.role-grid article{padding:8px;border-radius:7px;background:#281a23}.role-grid span{display:block;color:#9d8993;font-size:8px}.role-grid strong{font-size:17px}.checks,.issues{margin:0 14px 13px}.checks h4,.issues h4{margin:0 0 7px}.checks>div{display:grid;grid-template-columns:repeat(2,1fr);gap:5px}.checks span{padding:7px;border-radius:6px;font-size:9px}.ok{color:#7dd8c4;background:#15372f}.fail{color:#f099ab;background:#3a1b27}.issues>article{margin:5px 0;padding:8px;border:1px solid #5a3d4a;border-radius:7px;background:#2b1922}.issues>article.warning{border-color:#6a542d;background:#2b2214}.issues article header{display:flex;gap:7px}.issues article b{color:#eb9cb1;font-size:8px}.issues .warning b{color:#e2be72}.issues code{color:#ccb9c1;font-size:9px}.issues article>span{display:block;margin-top:3px;color:#917d86;font-size:9px}.issues p{margin:2px 0 0;color:#c1b1b8;font-size:10px}
@media(max-width:1050px){.workspace-grid{grid-template-columns:1fr}.editor-card{position:static}textarea{min-height:450px}}@media(max-width:720px){.review-page{padding:18px 12px}.hero,.truth-lock,.selector-bar{align-items:flex-start;flex-direction:column}.selector-bar label{width:100%}.metrics,.role-grid{grid-template-columns:repeat(2,1fr)}.checks>div,.identity-grid,.safety-grid{grid-template-columns:1fr}}
</style>
