import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = path.resolve(import.meta.dirname, '..', '..');

function readJson(relativePath: string): Record<string, any> {
  return JSON.parse(fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')) as Record<string, any>;
}

describe('professional text capability and progress audit', () => {
  it('covers all 15 VideoTypes without promoting fixtures or pending review artifacts', () => {
    const matrix = readJson('data/reports/story-agent-professional-text-capability-matrix.json');

    expect(matrix.schema_version).toBe('story-agent-professional-text-capability-matrix/v1');
    expect(matrix.video_types).toHaveLength(15);
    expect(new Set(matrix.video_types.map((item: Record<string, unknown>) => item.video_type)).size).toBe(15);
    expect(matrix.summary).toMatchObject({
      video_type_coverage_count: 15,
      legacy_profile_contract_count: 15,
      legacy_structural_generation_count: 15,
      professional_text_package_contract_count: 15,
      professional_text_package_skeleton_schema_pass_count: 15,
      professional_weighted_quality_hard_gate_count: 15,
      professional_text_package_pass_count: 0,
      golden_card_draft_count: 30,
      human_approved_golden_card_count: 0,
      fixture_regression_count: 9,
      professional_vertical_pipeline_type_count: 15,
      professional_quality_evaluator_type_count: 15,
      professional_revision_planner_type_count: 15,
      fixed_project_spec_count: 5,
      failure_fixture_count: 3,
      historical_drama_fixed_project_spec_count: 5,
      historical_drama_failure_fixture_count: 3,
      legend_story_fixed_project_spec_count: 5,
      legend_story_failure_fixture_count: 3,
      children_story_fixed_project_spec_count: 5,
      children_story_failure_fixture_count: 3,
      ai_comic_drama_fixed_project_spec_count: 5,
      ai_comic_drama_failure_fixture_count: 3,
      culture_promo_fixed_project_spec_count: 5,
      culture_promo_failure_fixture_count: 3,
      heritage_promo_fixed_project_spec_count: 5,
      heritage_promo_failure_fixture_count: 3,
      city_brand_promo_fixed_project_spec_count: 5,
      city_brand_promo_failure_fixture_count: 3,
      social_short_fixed_project_spec_count: 5,
      social_short_failure_fixture_count: 3,
      documentary_short_fixed_project_spec_count: 5,
      documentary_short_failure_fixture_count: 3,
      explainer_video_fixed_project_spec_count: 5,
      explainer_video_failure_fixture_count: 3,
      lecture_video_fixed_project_spec_count: 5,
      lecture_video_failure_fixture_count: 3,
      education_training_fixed_project_spec_count: 5,
      education_training_failure_fixture_count: 3,
      scene_short_fixed_project_spec_count: 5,
      scene_short_failure_fixture_count: 3,
      landscape_mood_fixed_project_spec_count: 5,
      landscape_mood_failure_fixture_count: 3,
      fixed_project_spec_total_count: 75,
      failure_fixture_total_count: 45,
      benchmark_preflight_type_count: 1,
      benchmark_source_snapshot_ready_count: 5,
      bridge_activation_plan_ready_count: 5,
      strict_technical_ready_count: 5,
      real_model_execution_ready_count: 0,
      benchmark_prompt_contract_type_count: 1,
      strict_scene_output_contract_type_count: 1,
      strict_real_model_bridge_type_count: 1,
      benchmark_run_ledger_type_count: 1,
      artifact_integrity_contract_type_count: 1,
      blind_review_threshold_contract_type_count: 1,
      controlled_runner_type_count: 1,
      controlled_run_plan_project_count: 5,
      prepared_run_ledger_count: 5,
      controlled_blocked_run_count: 5,
      post_initial_coordinator_type_count: 1,
      finalization_candidate_gate_type_count: 1,
      lifecycle_plan_type_count: 1,
      lifecycle_plan_project_count: 5,
      lifecycle_awaiting_verified_initial_count: 5,
      finalization_candidate_count: 0,
      signed_release_count: 0,
      model_invocation_count: 0,
      real_model_completed_count: 0,
      fixed_real_model_regression_project_count: 0,
      human_blind_review_pass_project_count: 0,
      professional_capability_hard_gate_failure_type_count: 15,
      multi_round_revision_contract_implemented: true,
      multi_round_revision_project_spec_count: 15,
      completed_two_round_verified_project_count: 0,
      recorded_verified_revision_round_count: 0,
      multi_round_revision_failure_fixture_count: 3,
      multi_round_revision_execution_implemented: true,
      planned_revision_round_count: 30,
      blocked_revision_project_count: 15,
      ready_for_round_1_project_count: 0,
    });
    expect(matrix.audit_policy.fixture_or_simulation_counts_as_professional_pass).toBe(false);
    expect(matrix.video_types.every((item: Record<string, unknown>) =>
      item.professional_text_package_passed === false
    )).toBe(true);
    expect(matrix.video_types.every((item: Record<string, unknown>) =>
      item.professional_text_package_contract_implemented === true
      && item.professional_text_package_skeleton_schema_passed === true
    )).toBe(true);
    expect(matrix.video_types.find((item: Record<string, unknown>) =>
      item.video_type === 'character_story'
    )).toMatchObject({
      professional_vertical_pipeline_implemented: true,
      quality_support: {
        professional_quality_evaluator_implemented: true,
      },
      repair_support: {
        professional_revision_plan_implemented: true,
        deterministic_derived_text_rebuild_implemented: true,
      },
      material_and_benchmark_support: {
        fixed_project_spec_count: 5,
        failure_fixture_count: 3,
        benchmark_preflight_implemented: true,
        benchmark_source_snapshot_ready_count: 5,
        bridge_activation_plan_ready_count: 5,
        strict_technical_ready_count: 5,
        strict_technical_readiness: true,
        real_model_execution_ready_count: 0,
        real_model_adapter_configured: false,
        real_model_execution_authorized: false,
        benchmark_prompt_contract_implemented: true,
        strict_scene_output_contract_implemented: true,
        strict_real_model_bridge_implemented: true,
        benchmark_run_ledger_implemented: true,
        artifact_integrity_contract_implemented: true,
        blind_review_threshold_contract_implemented: true,
        controlled_runner_implemented: true,
        controlled_run_plan_project_count: 5,
        prepared_run_ledger_count: 5,
        controlled_blocked_run_count: 5,
        post_initial_coordinator_implemented: true,
        finalization_candidate_gate_implemented: true,
        lifecycle_plan_implemented: true,
        lifecycle_plan_project_count: 5,
        lifecycle_awaiting_verified_initial_count: 5,
        finalization_candidate_count: 0,
        signed_release_count: 0,
        model_invocation_count: 0,
        real_model_completed_count: 0,
        fixed_real_model_regression_project_count: 0,
      },
      professional_text_package_passed: false,
    });
    expect(matrix.video_types.find((item: Record<string, unknown>) =>
      item.video_type === 'historical_drama'
    )).toMatchObject({
      professional_vertical_pipeline_implemented: true,
      quality_support: {
        professional_quality_evaluator_implemented: true,
      },
      repair_support: {
        professional_revision_plan_implemented: true,
        deterministic_derived_text_rebuild_implemented: true,
      },
      material_and_benchmark_support: {
        fixed_project_spec_count: 5,
        failure_fixture_count: 3,
        fixed_real_model_regression_project_count: 0,
        human_blind_review_pass_project_count: 0,
      },
      professional_text_package_passed: false,
    });
    expect(matrix.video_types.find((item: Record<string, unknown>) =>
      item.video_type === 'legend_story'
    )).toMatchObject({
      professional_vertical_pipeline_implemented: true,
      quality_support: {
        professional_quality_evaluator_implemented: true,
      },
      repair_support: {
        professional_revision_plan_implemented: true,
        deterministic_derived_text_rebuild_implemented: true,
      },
      material_and_benchmark_support: {
        fixed_project_spec_count: 5,
        failure_fixture_count: 3,
        fixed_real_model_regression_project_count: 0,
        human_blind_review_pass_project_count: 0,
      },
      professional_text_package_passed: false,
    });
    expect(matrix.video_types.find((item: Record<string, unknown>) =>
      item.video_type === 'children_story'
    )).toMatchObject({
      professional_vertical_pipeline_implemented: true,
      quality_support: {
        professional_quality_evaluator_implemented: true,
      },
      repair_support: {
        professional_revision_plan_implemented: true,
        deterministic_derived_text_rebuild_implemented: true,
      },
      material_and_benchmark_support: {
        fixed_project_spec_count: 5,
        failure_fixture_count: 3,
        fixed_real_model_regression_project_count: 0,
        human_blind_review_pass_project_count: 0,
      },
      professional_text_package_passed: false,
    });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'ai_comic_drama')).toMatchObject({
      professional_vertical_pipeline_implemented: true,
      quality_support: { professional_quality_evaluator_implemented: true },
      repair_support: { professional_revision_plan_implemented: true, deterministic_derived_text_rebuild_implemented: true },
      material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3, fixed_real_model_regression_project_count: 0 },
      professional_text_package_passed: false,
    });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'culture_promo')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'city_brand_promo')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'social_short')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'documentary_short')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'explainer_video')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'lecture_video')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'education_training')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'scene_short')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types.find((item: Record<string, unknown>) => item.video_type === 'landscape_mood')).toMatchObject({ professional_vertical_pipeline_implemented: true, quality_support: { professional_quality_evaluator_implemented: true }, repair_support: { professional_revision_plan_implemented: true }, material_and_benchmark_support: { fixed_project_spec_count: 5, failure_fixture_count: 3 }, professional_text_package_passed: false });
    expect(matrix.video_types
      .filter((item: Record<string, any>) => item.material_and_benchmark_support.fixture_regression_count > 0)
      .every((item: Record<string, any>) =>
        item.material_and_benchmark_support.fixture_counted_as_professional_pass === false
      )).toBe(true);
  });

  it('derives the independent progress baseline from weighted evidence units', () => {
    const progress = readJson('data/reports/story-agent-professional-text-creation-progress.json');
    const dimensions = progress.dimensions as Array<{
      weight_percent: number;
      completed_evidence_units: number;
      total_evidence_units: number;
      earned_percent: number;
    }>;

    expect(progress.schema_version).toBe('story-agent-professional-text-creation-progress/v1');
    expect(progress.current_stage).toMatchObject({
      stage_id: 'stage_6',
      iteration_id: 'p22_stage8_control_tower_and_external_handoff',
      status: 'stage6_real_execution_blocked_stage8_75_external_next_memory_handoff_zero_credit',
    });
    expect(dimensions.reduce((sum, item) => sum + item.weight_percent, 0)).toBe(100);
    expect(dimensions.reduce((sum, item) => sum + item.earned_percent, 0))
      .toBe(progress.professional_text_creation_progress_percent);
    expect(progress.progress_change).toMatchObject({
      previous_percent: 47.5,
      current_percent: 47.5,
    });
    expect(progress.professional_text_creation_progress_percent).toBe(47.5);
    expect(progress.metrics).toMatchObject({
      covered_video_type_count: 15,
      professional_text_package_contract_count: 15,
      professional_text_package_skeleton_schema_pass_count: 15,
      professional_text_package_pass_count: 0,
      professional_vertical_pipeline_type_count: 15,
      professional_quality_evaluator_type_count: 15,
      professional_revision_planner_type_count: 15,
      fixed_project_spec_count: 5,
      failure_fixture_count: 3,
      historical_drama_fixed_project_spec_count: 5,
      historical_drama_failure_fixture_count: 3,
      legend_story_fixed_project_spec_count: 5,
      legend_story_failure_fixture_count: 3,
      children_story_fixed_project_spec_count: 5,
      children_story_failure_fixture_count: 3,
      ai_comic_drama_fixed_project_spec_count: 5,
      ai_comic_drama_failure_fixture_count: 3,
      culture_promo_fixed_project_spec_count: 5,
      culture_promo_failure_fixture_count: 3,
      heritage_promo_fixed_project_spec_count: 5,
      heritage_promo_failure_fixture_count: 3,
      city_brand_promo_fixed_project_spec_count: 5,
      city_brand_promo_failure_fixture_count: 3,
      social_short_fixed_project_spec_count: 5,
      social_short_failure_fixture_count: 3,
      documentary_short_fixed_project_spec_count: 5,
      documentary_short_failure_fixture_count: 3,
      explainer_video_fixed_project_spec_count: 5,
      explainer_video_failure_fixture_count: 3,
      lecture_video_fixed_project_spec_count: 5,
      lecture_video_failure_fixture_count: 3,
      education_training_fixed_project_spec_count: 5,
      education_training_failure_fixture_count: 3,
      scene_short_fixed_project_spec_count: 5,
      scene_short_failure_fixture_count: 3,
      landscape_mood_fixed_project_spec_count: 5,
      landscape_mood_failure_fixture_count: 3,
      fixed_project_spec_total_count: 75,
      failure_fixture_total_count: 45,
      benchmark_preflight_type_count: 1,
      benchmark_source_snapshot_ready_count: 5,
      bridge_activation_plan_ready_count: 5,
      strict_technical_ready_count: 5,
      real_model_execution_ready_count: 0,
      benchmark_prompt_contract_type_count: 1,
      strict_scene_output_contract_type_count: 1,
      strict_real_model_bridge_type_count: 1,
      benchmark_run_ledger_type_count: 1,
      artifact_integrity_contract_type_count: 1,
      blind_review_threshold_contract_type_count: 1,
      controlled_runner_type_count: 1,
      controlled_run_plan_project_count: 5,
      prepared_run_ledger_count: 5,
      controlled_blocked_run_count: 5,
      post_initial_coordinator_type_count: 1,
      finalization_candidate_gate_type_count: 1,
      lifecycle_plan_type_count: 1,
      lifecycle_plan_project_count: 5,
      lifecycle_awaiting_verified_initial_count: 5,
      finalization_candidate_count: 0,
      signed_release_count: 0,
      model_invocation_count: 0,
      real_model_completed_count: 0,
      fixed_regression_project_count: 0,
      human_blind_review_pass_project_count: 0,
      human_approved_golden_card_count: 0,
      hard_gate_failure_count: 15,
      evaluated_professional_output_count: 0,
      local_candidate_fixture_evaluation_count: 15,
      failure_fixture_evaluation_count: 45,
      fixture_regression_count_excluded_from_professional_pass: 9,
      multi_round_revision_contract_implemented: true,
      multi_round_revision_project_spec_count: 15,
      completed_two_round_verified_project_count: 0,
      recorded_verified_revision_round_count: 0,
      multi_round_revision_failure_fixture_count: 3,
      multi_round_revision_execution_implemented: true,
      planned_revision_round_count: 30,
      blocked_revision_project_count: 15,
      ready_for_round_1_project_count: 0,
      stage6_real_input_intake_contract_implemented: true,
      stage6_real_input_project_count: 15,
      stage6_real_input_ready_project_count: 0,
      stage6_real_input_blocked_project_count: 15,
      stage6_revision_batch_executor_implemented: true,
      stage6_revision_batch_real_execution_count: 0,
      stage6_revision_workspace_implemented: true,
      stage6_revision_workspace_professional_pass_count: 0,
      stage6_real_revision_exit_audit_implemented: true,
      stage6_exit_audit_blocked_project_count: 15,
      stage6_exit_review_candidate_project_count: 0,
      stage6_exit_audit_verified_real_revision_round_count: 0,
      stage6_exit_audit_professional_pass_count: 0,
      unified_story_agent_ci_implemented: true,
      unified_story_agent_ci_local_passed: true,
      unified_story_agent_ci_paid_model_invocation_allowed: false,
      professional_workflow_product_surface_count: 8,
      stage6_operator_intake_workspace_implemented: true,
      stage6_operator_intake_ready_project_count: 0,
      stage6_operator_intake_blocked_project_count: 15,
      stage6_operator_intake_input_persisted: false,
      stage6_operator_intake_execution_started: false,
      stage6_operator_intake_professional_pass_count: 0,
      stage6_revision_preflight_workspace_implemented: true,
      stage6_revision_preflight_p0_ready_project_count: 0,
      stage6_revision_preflight_execute_endpoint_available: false,
      stage6_revision_preflight_artifacts_written: false,
      stage6_revision_preflight_execution_started: false,
      stage6_revision_preflight_verified_real_revision_credit_count: 0,
      stage6_revision_preflight_professional_pass_count: 0,
      stage6_exit_audit_workspace_implemented: true,
      stage6_exit_audit_workspace_read_only: true,
      stage6_exit_audit_workspace_blocked_project_count: 15,
      stage6_exit_audit_workspace_candidate_project_count: 0,
      stage6_exit_audit_workspace_verified_real_revision_round_count: 0,
      stage6_exit_audit_workspace_mutation_endpoint_available: false,
      stage6_exit_audit_workspace_professional_pass_count: 0,
      stage6_professional_package_inspector_implemented: true,
      stage6_professional_package_inspector_supported_video_type_count: 15,
      stage6_professional_package_inspector_template_schema_valid: true,
      stage6_professional_package_inspector_template_p0_package_gate_passed: false,
      stage6_professional_package_inspector_source_and_canonical_hash_distinct: true,
      stage6_professional_package_inspector_input_persisted: false,
      stage6_professional_package_inspector_p0_readiness_granted: false,
      stage6_professional_package_inspector_execution_started: false,
      stage6_professional_package_inspector_self_reported_professional_pass_is_credit: false,
      stage6_professional_package_inspector_professional_pass_count: 0,
      stage6_operator_control_tower_implemented: true,
      stage6_operator_control_tower_lane_count: 5,
      stage6_operator_control_tower_project_count: 15,
      stage6_operator_control_tower_external_handoff_project_count: 15,
      stage6_operator_control_tower_p0_ready_project_count: 0,
      stage6_operator_control_tower_verified_real_revision_round_count: 0,
      stage6_operator_control_tower_exit_candidate_project_count: 0,
      stage6_operator_control_tower_handoff_package_persisted: false,
      stage6_operator_control_tower_execute_endpoint_available: false,
      stage6_operator_control_tower_handoff_counts_as_external_input_completion: false,
      stage6_operator_control_tower_professional_pass_count: 0,
      stage6_table_read_evidence_inspector_implemented: true,
      stage6_table_read_evidence_inspector_project_count: 15,
      stage6_table_read_evidence_inspector_p0_ready_project_count: 0,
      stage6_table_read_evidence_inspector_template_signature_preflight_ready: false,
      stage6_table_read_evidence_inspector_input_persisted: false,
      stage6_table_read_evidence_inspector_state_mutated: false,
      stage6_table_read_evidence_inspector_signature_created: false,
      stage6_table_read_evidence_inspector_human_table_read_credit_count: 0,
      stage6_table_read_evidence_inspector_self_reported_signature_or_credit_accepted: false,
      stage6_table_read_evidence_inspector_sign_endpoint_available: false,
      stage6_table_read_evidence_inspector_execution_started: false,
      stage6_table_read_evidence_inspector_professional_pass_count: 0,
      stage6_exit_review_signature_inspector_implemented: true,
      stage6_exit_review_signature_inspector_project_count: 15,
      stage6_exit_review_signature_inspector_exit_candidate_project_count: 0,
      stage6_exit_review_signature_inspector_trust_policy_status: 'preparation_template',
      stage6_exit_review_signature_inspector_trusted_signer_count: 0,
      stage6_exit_review_signature_inspector_verified_role_count: 0,
      stage6_exit_review_signature_inspector_valid_signature_fixture_count_excluded_from_real_signature: 1,
      stage6_exit_review_signature_inspector_signature_created: false,
      stage6_exit_review_signature_inspector_attestation_persisted: false,
      stage6_exit_review_signature_inspector_exit_record_persisted: false,
      stage6_exit_review_signature_inspector_execution_started: false,
      stage6_exit_review_signature_inspector_sign_endpoint_available: false,
      stage6_exit_review_signature_inspector_import_endpoint_available: false,
      stage6_exit_review_signature_inspector_professional_pass_count: 0,
      stage7_golden_card_review_intake_implemented: true,
      stage7_golden_card_indexed_candidate_count: 30,
      stage7_golden_card_candidate_video_type_count: 3,
      stage7_golden_card_missing_video_type_count: 12,
      stage7_golden_card_missing_target_card_count: 60,
      stage7_golden_card_pending_human_review_count: 30,
      stage7_golden_card_approval_preflight_ready_count: 0,
      stage7_golden_card_human_approved_count: 0,
      stage7_golden_card_promoted_count: 0,
      stage7_golden_card_review_record_persisted: false,
      stage7_golden_card_source_card_modified: false,
      stage7_golden_card_province_markdown_modified: false,
      stage7_golden_card_approve_endpoint_available: false,
      stage7_golden_card_promote_endpoint_available: false,
      stage7_golden_card_professional_pass_count: 0,
      stage7_golden_card_candidate_expansion_implemented: true,
      stage7_golden_card_candidate_missing_video_type_count: 12,
      stage7_golden_card_candidate_planned_slot_count: 60,
      stage7_golden_card_candidate_benchmark_bound_slot_count: 60,
      stage7_golden_card_candidate_profile_bound_slot_count: 60,
      stage7_golden_card_candidate_import_ready_slot_count: 0,
      stage7_golden_card_authored_candidate_count: 0,
      stage7_golden_card_persisted_candidate_count: 0,
      stage7_golden_card_candidate_persisted: false,
      stage7_golden_card_candidate_index_modified: false,
      stage7_golden_card_candidate_source_card_file_created: false,
      stage7_golden_card_candidate_province_markdown_modified: false,
      stage7_golden_card_candidate_generate_endpoint_available: false,
      stage7_golden_card_candidate_persist_endpoint_available: false,
      stage7_golden_card_candidate_human_approved_count: 0,
      stage7_golden_card_candidate_professional_pass_count: 0,
      stage7_golden_card_review_signature_implemented: true,
      stage7_golden_card_review_signature_card_count: 30,
      stage7_golden_card_review_trust_policy_status: 'preparation_template',
      stage7_golden_card_review_trusted_signer_count: 0,
      stage7_golden_card_review_signature_verification_ready_count: 0,
      stage7_golden_card_review_valid_signature_fixture_count_excluded_from_human_approval: 1,
      stage7_golden_card_review_signature_created: false,
      stage7_golden_card_signed_review_persisted: false,
      stage7_golden_card_signature_source_card_modified: false,
      stage7_golden_card_signature_index_modified: false,
      stage7_golden_card_signature_province_markdown_modified: false,
      stage7_golden_card_review_sign_endpoint_available: false,
      stage7_golden_card_review_approve_endpoint_available: false,
      stage7_golden_card_review_signature_human_approved_count: 0,
      stage7_golden_card_review_signature_promoted_count: 0,
      stage7_golden_card_review_signature_professional_pass_count: 0,
      stage7_material_operations_control_tower_implemented: true,
      stage7_material_operations_lane_count: 5,
      stage7_material_operations_external_handoff_task_count: 51,
      stage7_material_operations_video_type_task_count: 12,
      stage7_material_operations_golden_card_task_count: 30,
      stage7_material_operations_domain_pack_task_count: 9,
      stage7_material_operations_source_binding_count: 6,
      stage7_material_operations_handoff_persisted: false,
      stage7_material_operations_execution_started: false,
      stage7_material_operations_handoff_counts_as_external_completion: false,
      stage7_domain_pack_candidate_count: 9,
      stage7_domain_pack_evidence_complete_count: 0,
      stage7_domain_pack_human_approved_count: 0,
      stage7_domain_pack_pre_signature_ready_count: 0,
      stage7_domain_pack_real_reviewer_submission_count: 0,
      stage7_domain_pack_real_signature_count: 0,
      stage7_domain_pack_formal_patch_count: 0,
      stage7_domain_pack_promoted_count: 0,
      stage7_material_operations_professional_pass_count: 0,
      stage8_blind_review_intake_implemented: true,
      stage8_blind_review_intake_video_type_count: 15,
      stage8_blind_review_intake_project_count: 75,
      stage8_blind_review_intake_source_binding_count: 15,
      stage8_blind_review_intake_ready_project_count: 0,
      stage8_blind_review_intake_blocked_project_count: 75,
      stage8_blind_review_reviewer_assignment_ready_project_count: 0,
      stage8_blind_review_human_pass_project_count: 0,
      stage8_blind_review_human_pass_project_target: 45,
      stage8_blind_review_template_provenance: 'preparation_template',
      stage8_blind_review_input_persisted: false,
      stage8_blind_review_record_persisted: false,
      stage8_blind_review_execution_started: false,
      stage8_blind_review_fixture_simulation_fallback_counts_as_real_review: false,
      stage8_blind_review_professional_pass_count: 0,
      stage8_blind_review_evaluator_v2_implemented: true,
      stage8_blind_review_evaluator_video_type_count: 15,
      stage8_blind_review_weight_contract_ready_count: 15,
      stage8_blind_review_weight_sum_valid_count: 15,
      stage8_blind_review_unique_weight_contract_sha256_count: 15,
      stage8_blind_review_evaluator_source_binding_count: 4,
      stage8_blind_review_bundle_schema_version: 'professional-benchmark-blind-review/v2',
      stage8_blind_review_decision_schema_version: 'professional-benchmark-blind-review-decision/v2',
      stage8_blind_review_artifact_schema_v2_bound: true,
      stage8_blind_review_finalization_weight_contract_bound: true,
      stage8_blind_review_shared_weight_reference_mutation_blocked: true,
      stage8_blind_review_real_bundle_count: 0,
      stage8_blind_review_score_threshold_counts_as_human_pass: false,
      stage8_blind_review_evaluator_human_pass_project_count: 0,
      stage8_blind_review_evaluator_professional_pass_count: 0,
      stage8_blind_review_signature_inspector_implemented: true,
      stage8_blind_review_signature_project_count: 75,
      stage8_blind_review_signature_required_role_count: 3,
      stage8_blind_review_signature_trust_policy_status: 'preparation_template',
      stage8_blind_review_signature_trusted_reviewer_count: 0,
      stage8_blind_review_signature_verification_ready_project_count: 0,
      stage8_blind_review_valid_signature_fixture_count_excluded_from_real_signature: 1,
      stage8_blind_review_real_signature_count: 0,
      stage8_blind_review_signature_created: false,
      stage8_blind_review_signed_review_persisted: false,
      stage8_blind_review_finalization_started: false,
      stage8_blind_review_signature_human_pass_project_count: 0,
      stage8_blind_review_signed_release_count: 0,
      stage8_blind_review_signature_professional_pass_count: 0,
      stage8_finalization_preflight_implemented: true,
      stage8_finalization_preflight_project_count: 75,
      stage8_finalization_artifact_ready_project_count: 0,
      stage8_finalization_revision_delta_ready_project_count: 0,
      stage8_finalization_signed_review_ready_project_count: 0,
      stage8_finalization_external_trust_ready_project_count: 0,
      stage8_finalization_candidate_ready_project_count: 0,
      stage8_finalization_signed_release_count: 0,
      stage8_finalization_professional_pass_count: 0,
      stage8_finalization_input_persisted: false,
      stage8_finalization_started: false,
      stage8_finalization_release_endpoint_available: false,
      stage8_durable_release_inspector_implemented: true,
      stage8_durable_release_project_count: 75,
      stage8_durable_release_finalization_candidate_ready_count: 0,
      stage8_durable_release_active_authority_count: 0,
      stage8_durable_release_verification_ready_count: 0,
      stage8_durable_release_imported_count: 0,
      stage8_durable_release_professional_pass_count: 0,
      stage8_durable_release_record_created: false,
      stage8_durable_release_record_persisted: false,
      stage8_durable_release_mutation_endpoint_available: false,
      stage8_durable_release_valid_signature_fixture_count: 0,
      stage8_operations_control_tower_implemented: true,
      stage8_operations_lane_count: 5,
      stage8_operations_project_count: 75,
      stage8_operations_unique_next_count: 75,
      stage8_operations_external_handoff_project_count: 75,
      stage8_operations_intake_ready_project_count: 0,
      stage8_operations_evaluator_contract_ready_video_type_count: 15,
      stage8_operations_real_review_bundle_count: 0,
      stage8_operations_signature_ready_project_count: 0,
      stage8_operations_finalization_candidate_ready_project_count: 0,
      stage8_operations_durable_release_verification_ready_project_count: 0,
      stage8_operations_durable_release_imported_count: 0,
      stage8_operations_human_blind_review_pass_count: 0,
      stage8_operations_handoff_persisted: false,
      stage8_operations_execution_started: false,
      stage8_operations_handoff_counts_as_external_completion: false,
      stage8_operations_mutation_endpoint_available: false,
      stage8_operations_professional_pass_count: 0,
    });
    expect(progress.parallel_governance_track).toMatchObject({
      excluded_from_professional_text_creation_progress: true,
      archive_or_rebuild_candidate_count: 827,
      soft_archive_signoff_exclusion_applied: true,
      soft_archive_signoff_excluded_count: 827,
      relink_candidate_count: 99,
      relink_triaged_count: 99,
      relink_resolved_count: 0,
      safe_auto_relink_count: 0,
      suffix_hint_manual_review_count: 9,
      target_external_ready_count: 0,
      target_local_acceptance_ready_count: 5,
      target_pending_external_artifact_count: 5,
      destructive_delete_count: 0,
      guessed_relink_count: 0,
    });
  });
});
