import fs from 'node:fs'; import path from 'node:path'; import { describe, expect, it } from 'vitest'; import { ProfessionalTextPackageSchema } from '@shared/schemas.js'; import type { StoryGenerateResult } from '@shared/types.js';
import { buildCulturePromoProfessionalTextPackage } from '../services/professional-culture-promo-pipeline-service.js'; import { buildCulturePromoRevisionPlan, rebuildCulturePromoDerivedText } from '../services/professional-culture-promo-revision-service.js'; import type { CulturePromoProfessionalEvidence } from '../services/professional-culture-promo-quality-service.js';
const repoRoot = path.resolve(import.meta.dirname, '..', '..', '..', '..');
function story(): StoryGenerateResult { const scenes = [
  ['一根线先出现','湘绣展示厅','黑色背景上，一根红线穿过空白绣面，画面先不解释名称。','镜头跟随红线穿过绣面。','观众先看到材料，不先听赞美。'],
  ['针脚改变方向','绣架旁','手部在同一片纹样上改变针脚方向，光泽随观看角度变化。','绣者转动绣架展示前后差异。','文化特点必须由动作和材料证明。'],
  ['线走进今天','设计工作台','年轻设计者把传统纹样拆成色块，放进当代日用品草图。','设计者把绣片与新草图并排。','当代连接不能只是口号。'],
  ['把一根线带走','公共体验空间','参观者在纸卡上画下一条自己的纹样线，红线从绣面延伸到卡片。','孩子把纹样卡递给身边的人。','行动召唤要从前文体验自然发生。']
].map(([title,location,plot,key_action,conflict],i)=>({scene_id:i+1,title,duration_sec:35,location,time_of_day:'白天',dramatic_function:['符号引入','文化证据','当代连接','行动召唤'][i],plot,key_action,characters:['绣者','参观者'],visual_prompt:`${location}，红线与针脚为视觉焦点。`,camera_suggestion:'微距动作与中景空间交替。',cultural_note:'湘绣事实与诗化表达分层。',conflict,dialogue_or_narration:['先看一根线。它还没有名字。','方向一变，光也跟着变。','传统不是停在玻璃后面，它进入今天的手。','从看见一根线开始，画下你的下一笔。'][i],source_entries:['湘绣——中国四大名绣之一'],factual_basis:'湘绣的丝线、针脚、色彩与绣面来自知识库条目。',fictionalized_elements:['具体人物、体验活动和镜头连接为宣传创作。']})); return {storyId:'culture-promo-fixture',title:'一根线的今天',generation_type:'scene_short',video_type:'culture_promo',presentation_style:'voiceover_montage',source_entry:'湘绣——中国四大名绣之一',logline:'从一根丝线出发，看湘绣的材料、动作和当代使用如何连接。',theme:'传统的生命力来自仍有人看见、使用并重新表达。',full_text:scenes.map(s=>`${s.title}。${s.plot}${s.dialogue_or_narration}`).join('\n\n'),scene_breakdown:scenes,gears_segments:[],gears_segments_url:'',cultural_constraints:['不虚构机构成果或具体传承人身份。'],credibility_note:'文化事实可核，人物与活动为宣传创作。',truth_mode:'inspired_by_material',story_structure:'object_clue_journey'}; }
function evidence(): CulturePromoProfessionalEvidence { return {communication_proposition:'一根线如何从材料、针脚走进今天的生活。',audience_takeaway:'湘绣不是抽象赞美，而是仍可被看见、使用和重新表达的文化语言。',visual_symbols:[{symbol_id:'red-thread',label:'红线',meaning:'从材料到观众行动的连接',scene_ids:[1,4]},{symbol_id:'stitch-light',label:'针脚光泽',meaning:'用可见变化证明技艺差异',scene_ids:[2,3]}],proof_points:[{proof_id:'p1',claim:'湘绣以丝线和针法形成绣面。',evidence_ids:['xiang-fact'],visible_expression:'微距丝线穿过绣面'},{proof_id:'p2',claim:'不同针脚方向产生不同视觉质感。',evidence_ids:['xiang-fact'],visible_expression:'转动绣架观察光泽'},{proof_id:'p3',claim:'传统纹样可进入当代设计表达。',evidence_ids:['xiang-modern'],visible_expression:'绣片与设计草图并排'}],information_curve:[1,2,3,4].map((scene_id,i)=>({scene_id,new_information:['材料是入口','动作证明特点','当代使用延续意义','观众可以参与表达'][i],audience_effect:['好奇','理解','关联今天','愿意行动'][i]})),voiceover_visual_division:['画面展示材料和动作，旁白只说明动作带来的意义。','画面出现当代物件，旁白不重复物件名称。'],modern_connection:'年轻设计者把纹样拆解为今天可使用的设计语言。',call_to_action:'在体验卡上画下自己的纹样线，并与身边的人分享。',slogan_or_key_sentence:'从一根线开始，让传统继续走向今天。',scene_turns:{'1':'从未知线条到文化入口','2':'从漂亮表面到动作证据','3':'从历史技艺到当代使用','4':'从观看到参与表达'}}; }
function input(): any { return {story:story(),target_audience:'18至35岁文化空间观众',platform:'文化主题形象短片',target_duration:'3分钟',communication_goal:'用具体视觉证据建立湘绣当代传播认知。',production_goal:'形成旁白和导演文本分工明确的宣传片。',audience_promise:'观众会从一根线看懂湘绣如何由材料、动作进入今天。',truth_mode:'inspired_by_material',research:{source_summary:'知识库提供湘绣材料、工艺与文化信息。',evidence_items:[{evidence_id:'xiang-fact',status:'verified_fact',claim:'湘绣使用丝线、针法和纹样形成绣面。',source:'湘绣——中国四大名绣之一',allowed_usage:'文化证据。',verification_note:'具体镜头需复核。'},{evidence_id:'xiang-modern',status:'plausible_dramatization',claim:'以设计草图和体验卡连接当代传播。',source:'宣传创作',allowed_usage:'当代连接。',verification_note:'不冒充真实项目成果。'}],unknowns:['具体机构活动和可拍空间待项目核验。'],authorization_notes:['不复制商业宣传片表达。']},promo_evidence:evidence(),now:'2026-07-11T05:00:00.000Z'}; }
const gates=(pkg:ReturnType<typeof buildCulturePromoProfessionalTextPackage>)=>pkg.quality_report.hard_gate_failures.map(x=>x.split(':',1)[0]);
describe('culture_promo professional pipeline',()=>{
it('builds an evidence-backed promo candidate without professional credit',()=>{const pkg=buildCulturePromoProfessionalTextPackage(input());expect(ProfessionalTextPackageSchema.safeParse(pkg).success).toBe(true);expect(pkg.status).toBe('in_review');expect(pkg.quality_report.hard_gate_failures).toEqual([]);expect(pkg.quality_report.total_score).toBeGreaterThanOrEqual(80);expect(pkg.quality_report.professional_passed).toBe(false);});
it('detects registered promo failure fixtures',()=>{const registry=JSON.parse(fs.readFileSync(path.join(repoRoot,'data/professional-benchmarks/culture-promo-stage3-iteration1-benchmark-specs.json'),'utf8'));for(const f of registry.failure_fixtures){const x=input();if(f.fixture_id.includes('empty-praise')){x.promo_evidence.communication_proposition='';x.promo_evidence.audience_takeaway='';x.promo_evidence.proof_points=[];}if(f.fixture_id.includes('symbol-wall')){x.promo_evidence.visual_symbols=[];x.promo_evidence.information_curve=[];x.promo_evidence.voiceover_visual_division=[];}if(f.fixture_id.includes('no-modern')){x.promo_evidence.modern_connection='';x.promo_evidence.call_to_action='';x.promo_evidence.slogan_or_key_sentence='';}const pkg=buildCulturePromoProfessionalTextPackage(x);const plan=buildCulturePromoRevisionPlan(pkg);expect(gates(pkg)).toEqual(expect.arrayContaining(f.expected_hard_gate_ids));expect(plan.actions.map((a:any)=>a.issue_id)).toEqual(expect.arrayContaining(f.expected_hard_gate_ids));}});
it('rebuilds stale derived promo text',()=>{const pkg=buildCulturePromoProfessionalTextPackage(input());pkg.sequence_beats=[];pkg.delivery_text_package.scene_units=[];const r=rebuildCulturePromoDerivedText({package:pkg,promo_evidence:evidence()});expect(r.rebuilt_sections).toEqual(['sequence_beats','delivery_text_package']);expect(r.package.quality_report.professional_passed).toBe(false);});
it('registers five pending real-model specs',()=>{const r=JSON.parse(fs.readFileSync(path.join(repoRoot,'data/professional-benchmarks/culture-promo-stage3-iteration1-benchmark-specs.json'),'utf8'));expect(r.summary).toMatchObject({fixed_project_spec_count:5,fixed_real_model_project_count:0,failure_fixture_count:3});expect(r.projects.every((x:any)=>x.status==='awaiting_real_model_run'&&!x.professional_passed)).toBe(true);});
});
